/**
 * 産地表記 → 生産国の検証済み対応。代表品種や「よくある産地」の推測は含めない。
 * 載せるのは法令・地理的表示（AOC / DOCG / DO / AVA / GI 等）で 1 か国に確定する産地だけ。
 * 複数国にまたがる名称（Tokaj は例外的に既存維持、Pisco 等）は載せない。
 * キーは正規化後（小文字・記号除去・`_` 区切り）。日本語の産地は JA 表で別に持つ。
 */

const FR = "フランス";
const IT = "イタリア";
const ES = "スペイン";
const PT = "ポルトガル";
const DE = "ドイツ";
const AT = "オーストリア";
const US = "アメリカ";
const AU = "オーストラリア";
const NZ = "ニュージーランド";
const CL = "チリ";
const AR = "アルゼンチン";
const ZA = "南アフリカ";
const GB = "イギリス";
const MX = "メキシコ";
const GR = "ギリシャ";
const HU = "ハンガリー";
const GE = "ジョージア";
const CA = "カナダ";
const BR = "ブラジル";
const JP = "日本";

const VERIFIED_ORIGIN_BY_APPELLATION: Record<string, string> = {
  // フランス（AOC / 地方）
  bordeaux: FR,
  champagne: FR,
  bourgogne: FR,
  burgundy: FR,
  alsace: FR,
  loire: FR,
  val_de_loire: FR,
  rhone: FR,
  cotes_du_rhone: FR,
  sancerre: FR,
  chablis: FR,
  beaujolais: FR,
  provence: FR,
  cote_de_nuit: FR,
  cote_de_nuits: FR,
  cote_de_beaune: FR,
  chateauneuf_du_pape: FR,
  medoc: FR,
  haut_medoc: FR,
  pauillac: FR,
  margaux: FR,
  saint_julien: FR,
  saint_estephe: FR,
  saint_emilion: FR,
  pomerol: FR,
  graves: FR,
  pessac_leognan: FR,
  sauternes: FR,
  barsac: FR,
  entre_deux_mers: FR,
  fronsac: FR,
  cotes_de_bordeaux: FR,
  gevrey_chambertin: FR,
  vosne_romanee: FR,
  nuits_saint_georges: FR,
  chambolle_musigny: FR,
  morey_saint_denis: FR,
  pommard: FR,
  volnay: FR,
  meursault: FR,
  puligny_montrachet: FR,
  chassagne_montrachet: FR,
  santenay: FR,
  mercurey: FR,
  givry: FR,
  rully: FR,
  macon: FR,
  macon_villages: FR,
  pouilly_fuisse: FR,
  pouilly_fume: FR,
  saint_veran: FR,
  petit_chablis: FR,
  morgon: FR,
  fleurie: FR,
  moulin_a_vent: FR,
  brouilly: FR,
  vouvray: FR,
  chinon: FR,
  bourgueil: FR,
  saumur: FR,
  anjou: FR,
  muscadet: FR,
  menetou_salon: FR,
  quincy: FR,
  touraine: FR,
  savennieres: FR,
  hermitage: FR,
  crozes_hermitage: FR,
  cote_rotie: FR,
  condrieu: FR,
  saint_joseph: FR,
  cornas: FR,
  gigondas: FR,
  vacqueyras: FR,
  tavel: FR,
  lirac: FR,
  ventoux: FR,
  luberon: FR,
  costieres_de_nimes: FR,
  languedoc: FR,
  roussillon: FR,
  corbieres: FR,
  minervois: FR,
  fitou: FR,
  faugeres: FR,
  saint_chinian: FR,
  pic_saint_loup: FR,
  picpoul_de_pinet: FR,
  limoux: FR,
  banyuls: FR,
  maury: FR,
  collioure: FR,
  cotes_du_roussillon: FR,
  bandol: FR,
  cassis: FR,
  cotes_de_provence: FR,
  cahors: FR,
  madiran: FR,
  jurancon: FR,
  gaillac: FR,
  bergerac: FR,
  monbazillac: FR,
  jura: FR,
  arbois: FR,
  chateau_chalon: FR,
  savoie: FR,
  corse: FR,
  corsica: FR,
  patrimonio: FR,
  cremant_d_alsace: FR,
  cremant_de_bourgogne: FR,
  cremant_de_loire: FR,
  cremant_de_limoux: FR,
  cremant_du_jura: FR,
  cognac: FR,
  armagnac: FR,
  calvados: FR,
  // イタリア（DOCG / DOC / 地方）
  barolo: IT,
  barbaresco: IT,
  chianti: IT,
  chianti_classico: IT,
  brunello: IT,
  brunello_di_montalcino: IT,
  rosso_di_montalcino: IT,
  vino_nobile_di_montepulciano: IT,
  rosso_di_montepulciano: IT,
  montepulciano_d_abruzzo: IT,
  prosecco: IT,
  valpolicella: IT,
  amarone: IT,
  amarone_della_valpolicella: IT,
  soave: IT,
  bardolino: IT,
  lugana: IT,
  franciacorta: IT,
  lambrusco: IT,
  langhe: IT,
  roero: IT,
  dogliani: IT,
  gavi: IT,
  asti: IT,
  moscato_d_asti: IT,
  barbera_d_asti: IT,
  barbera_d_alba: IT,
  nebbiolo_d_alba: IT,
  dolcetto_d_alba: IT,
  gattinara: IT,
  ghemme: IT,
  piemonte: IT,
  piedmont: IT,
  toscana: IT,
  tuscany: IT,
  bolgheri: IT,
  maremma_toscana: IT,
  morellino_di_scansano: IT,
  vernaccia_di_san_gimignano: IT,
  carmignano: IT,
  umbria: IT,
  montefalco: IT,
  sagrantino_di_montefalco: IT,
  orvieto: IT,
  marche: IT,
  verdicchio_dei_castelli_di_jesi: IT,
  verdicchio_di_matelica: IT,
  conero: IT,
  abruzzo: IT,
  puglia: IT,
  apulia: IT,
  primitivo_di_manduria: IT,
  salice_salentino: IT,
  salento: IT,
  castel_del_monte: IT,
  campania: IT,
  taurasi: IT,
  fiano_di_avellino: IT,
  greco_di_tufo: IT,
  falanghina_del_sannio: IT,
  basilicata: IT,
  aglianico_del_vulture: IT,
  sicilia: IT,
  sicily: IT,
  etna: IT,
  cerasuolo_di_vittoria: IT,
  marsala: IT,
  sardegna: IT,
  sardinia: IT,
  vermentino_di_gallura: IT,
  cannonau_di_sardegna: IT,
  veneto: IT,
  valdobbiadene: IT,
  conegliano_valdobbiadene: IT,
  alto_adige: IT,
  sudtirol: IT,
  trentino: IT,
  trento: IT,
  friuli: IT,
  friuli_venezia_giulia: IT,
  collio: IT,
  colli_orientali_del_friuli: IT,
  lombardia: IT,
  lombardy: IT,
  valtellina: IT,
  oltrepo_pavese: IT,
  emilia_romagna: IT,
  romagna: IT,
  liguria: IT,
  cinque_terre: IT,
  lazio: IT,
  frascati: IT,
  molise: IT,
  calabria: IT,
  ciro: IT,
  valle_d_aosta: IT,
  grappa: IT,
  // スペイン（DO / DOCa）
  rioja: ES,
  ribera_del_duero: ES,
  priorat: ES,
  priorato: ES,
  cava: ES,
  rias_baixas: ES,
  jerez: ES,
  sherry: ES,
  manzanilla_sanlucar_de_barrameda: ES,
  toro: ES,
  bierzo: ES,
  rueda: ES,
  navarra: ES,
  penedes: ES,
  jumilla: ES,
  yecla: ES,
  la_mancha: ES,
  valdepenas: ES,
  montsant: ES,
  somontano: ES,
  campo_de_borja: ES,
  carinena: ES,
  calatayud: ES,
  valencia: ES,
  utiel_requena: ES,
  alicante: ES,
  ribeira_sacra: ES,
  ribeiro: ES,
  valdeorras: ES,
  monterrei: ES,
  txakoli: ES,
  getariako_txakolina: ES,
  cigales: ES,
  costers_del_segre: ES,
  emporda: ES,
  terra_alta: ES,
  malaga: ES,
  montilla_moriles: ES,
  vinos_de_madrid: ES,
  castilla_y_leon: ES,
  castilla_la_mancha: ES,
  // ポルトガル
  porto: PT,
  port: PT,
  douro: PT,
  vinho_verde: PT,
  dao: PT,
  alentejo: PT,
  bairrada: PT,
  madeira: PT,
  lisboa: PT,
  tejo: PT,
  setubal: PT,
  algarve: PT,
  tras_os_montes: PT,
  beira_interior: PT,
  colares: PT,
  bucelas: PT,
  // ドイツ
  mosel: DE,
  rheingau: DE,
  pfalz: DE,
  rheinhessen: DE,
  nahe: DE,
  franken: DE,
  baden: DE,
  wurttemberg: DE,
  ahr: DE,
  mittelrhein: DE,
  saale_unstrut: DE,
  sachsen: DE,
  hessische_bergstrasse: DE,
  // オーストリア
  wachau: AT,
  kamptal: AT,
  kremstal: AT,
  traisental: AT,
  wagram: AT,
  weinviertel: AT,
  burgenland: AT,
  neusiedlersee: AT,
  leithaberg: AT,
  mittelburgenland: AT,
  steiermark: AT,
  sudsteiermark: AT,
  vulkanland_steiermark: AT,
  thermenregion: AT,
  carnuntum: AT,
  niederosterreich: AT,
  wien: AT,
  // アメリカ（AVA / 州 / 蒸留酒）
  napa: US,
  napa_valley: US,
  sonoma: US,
  sonoma_county: US,
  sonoma_coast: US,
  russian_river_valley: US,
  alexander_valley: US,
  dry_creek_valley: US,
  carneros: US,
  los_carneros: US,
  oakville: US,
  rutherford: US,
  stags_leap_district: US,
  howell_mountain: US,
  st_helena: US,
  saint_helena: US,
  calistoga: US,
  paso_robles: US,
  santa_barbara_county: US,
  santa_ynez_valley: US,
  sta_rita_hills: US,
  santa_maria_valley: US,
  santa_cruz_mountains: US,
  monterey: US,
  santa_lucia_highlands: US,
  central_coast: US,
  north_coast: US,
  lodi: US,
  sierra_foothills: US,
  mendocino: US,
  anderson_valley: US,
  livermore_valley: US,
  california: US,
  oregon: US,
  willamette_valley: US,
  dundee_hills: US,
  washington_state: US,
  columbia_valley: US,
  walla_walla_valley: US,
  yakima_valley: US,
  red_mountain: US,
  horse_heaven_hills: US,
  finger_lakes: US,
  long_island: US,
  north_fork_of_long_island: US,
  virginia: US,
  texas_hill_country: US,
  kentucky: US,
  kentucky_straight_bourbon: US,
  bourbon: US,
  tennessee_whiskey: US,
  tennessee: US,
  // オーストラリア
  barossa: AU,
  barossa_valley: AU,
  eden_valley: AU,
  clare_valley: AU,
  mclaren_vale: AU,
  adelaide_hills: AU,
  coonawarra: AU,
  langhorne_creek: AU,
  padthaway: AU,
  south_australia: AU,
  yarra_valley: AU,
  mornington_peninsula: AU,
  heathcote: AU,
  rutherglen: AU,
  geelong: AU,
  king_valley: AU,
  victoria: AU,
  hunter_valley: AU,
  hunter: AU,
  orange: AU,
  mudgee: AU,
  canberra_district: AU,
  new_south_wales: AU,
  margaret_river: AU,
  great_southern: AU,
  frankland_river: AU,
  swan_valley: AU,
  western_australia: AU,
  tasmania: AU,
  // ニュージーランド
  marlborough: NZ,
  central_otago: NZ,
  hawke_s_bay: NZ,
  hawkes_bay: NZ,
  martinborough: NZ,
  wairarapa: NZ,
  nelson: NZ,
  gisborne: NZ,
  waipara: NZ,
  north_canterbury: NZ,
  waiheke_island: NZ,
  kumeu: NZ,
  // チリ
  maipo: CL,
  maipo_valley: CL,
  valle_del_maipo: CL,
  colchagua: CL,
  colchagua_valley: CL,
  valle_de_colchagua: CL,
  casablanca_valley: CL,
  valle_de_casablanca: CL,
  aconcagua: CL,
  aconcagua_valley: CL,
  maule: CL,
  maule_valley: CL,
  valle_del_maule: CL,
  rapel: CL,
  rapel_valley: CL,
  cachapoal: CL,
  curico: CL,
  curico_valley: CL,
  leyda: CL,
  leyda_valley: CL,
  san_antonio_valley: CL,
  limari: CL,
  limari_valley: CL,
  elqui: CL,
  elqui_valley: CL,
  itata: CL,
  bio_bio: CL,
  central_valley_chile: CL,
  valle_central: CL,
  // アルゼンチン
  mendoza: AR,
  lujan_de_cuyo: AR,
  maipu: AR,
  valle_de_uco: AR,
  uco_valley: AR,
  tupungato: AR,
  gualtallary: AR,
  salta: AR,
  cafayate: AR,
  san_juan: AR,
  la_rioja_argentina: AR,
  rio_negro: AR,
  neuquen: AR,
  // 南アフリカ
  stellenbosch: ZA,
  swartland: ZA,
  paarl: ZA,
  franschhoek: ZA,
  constantia: ZA,
  walker_bay: ZA,
  hemel_en_aarde: ZA,
  elgin: ZA,
  robertson: ZA,
  wellington_south_africa: ZA,
  western_cape: ZA,
  coastal_region: ZA,
  breedekloof: ZA,
  tulbagh: ZA,
  darling: ZA,
  // イギリス（スコッチ / 英国産スパークリング）
  scotch: GB,
  scotch_whisky: GB,
  scotland: GB,
  speyside: GB,
  islay: GB,
  highland: GB,
  highlands: GB,
  lowland: GB,
  lowlands: GB,
  campbeltown: GB,
  isle_of_skye: GB,
  orkney: GB,
  english_sparkling_wine: GB,
  english_wine: GB,
  // メキシコ
  tequila: MX,
  mezcal: MX,
  jalisco: MX,
  oaxaca: MX,
  valle_de_guadalupe: MX,
  baja_california: MX,
  // ギリシャ
  santorini: GR,
  nemea: GR,
  naoussa: GR,
  mantinia: GR,
  amynteo: GR,
  crete: GR,
  peloponnese: GR,
  macedonia_greece: GR,
  // ハンガリー（Tokaj は既存維持。スロバキア側の表記は "Tokajska" で別）
  tokaj: HU,
  tokaji: HU,
  eger: HU,
  villany: HU,
  szekszard: HU,
  somlo: HU,
  badacsony: HU,
  // ジョージア
  kakheti: GE,
  // カナダ
  okanagan_valley: CA,
  okanagan: CA,
  niagara_peninsula: CA,
  niagara: CA,
  prince_edward_county: CA,
  // ブラジル
  cachaca: BR,
  vale_dos_vinhedos: BR,
  // 日本（ローマ字表記）
  yamanashi: JP,
  koshu_yamanashi: JP,
  nagano: JP,
  hokkaido: JP,
  yamagata: JP,
  niigata: JP,
  nada: JP,
  fushimi: JP,
  hakusan: JP,
  yoichi: JP,
  japanese_whisky: JP,
  japanese_sake: JP,
  nihonshu: JP,
  osaka: JP,
  hyogo: JP,
  kyoto: JP,
  hiroshima: JP,
  akita: JP,
  fukushima: JP,
  miyagi: JP,
  iwate: JP,
  aomori: JP,
  shizuoka: JP,
  saga: JP,
  kagoshima: JP,
  okinawa: JP,
  kumamoto: JP,
  oita: JP,
  miyazaki: JP,
  nagasaki: JP,
  fukuoka: JP,
  ishikawa: JP,
  toyama: JP,
  fukui: JP,
  shiga: JP,
  nara: JP,
  wakayama: JP,
  mie: JP,
  gifu: JP,
  aichi: JP,
  tochigi: JP,
  ibaraki: JP,
  gunma: JP,
  saitama: JP,
  chiba: JP,
  tokyo: JP,
  kanagawa: JP,
  tottori: JP,
  shimane: JP,
  okayama: JP,
  yamaguchi: JP,
  tokushima: JP,
  kagawa: JP,
  ehime: JP,
  kochi: JP,
};

/**
 * 日本語の産地表記（都道府県・清酒 / ワイン産地の地理的表示）。完全一致だけ。
 * 「日本酒」「焼酎」のような種類名は入れない（種類だけでは国を断定しない）。
 */
const VERIFIED_ORIGIN_BY_JA_APPELLATION: Record<string, string> = Object.fromEntries(
  [
    "北海道",
    "青森",
    "岩手",
    "宮城",
    "秋田",
    "山形",
    "福島",
    "茨城",
    "栃木",
    "群馬",
    "埼玉",
    "千葉",
    "東京",
    "神奈川",
    "新潟",
    "富山",
    "石川",
    "福井",
    "山梨",
    "長野",
    "岐阜",
    "静岡",
    "愛知",
    "三重",
    "滋賀",
    "京都",
    "大阪",
    "兵庫",
    "奈良",
    "和歌山",
    "鳥取",
    "島根",
    "岡山",
    "広島",
    "山口",
    "徳島",
    "香川",
    "愛媛",
    "高知",
    "福岡",
    "佐賀",
    "長崎",
    "熊本",
    "大分",
    "宮崎",
    "鹿児島",
    "沖縄",
    "灘",
    "灘五郷",
    "伏見",
    "白山",
    "山形正宗",
    "はりま",
    "三重の酒",
    "利根沼田",
    "萩",
    "余市",
    "北海道余市",
    "大阪ワイン",
    "長野ワイン",
    "山梨ワイン",
    "甲州市",
    "壱岐",
    "球磨",
    "琉球",
    "薩摩",
    "ジャパニーズウイスキー",
  ].map((name) => [name, JP]),
);

/** 「Barolo DOCG」「Appellation Margaux Contrôlée」の格付け語。国を決める情報ではないので落とす */
const QUALIFIER_TOKENS = new Set([
  "docg",
  "doc",
  "dop",
  "igt",
  "igp",
  "aoc",
  "aop",
  "ava",
  "ao",
  "do",
  "doca",
  "doq",
  "dp",
  "vdqs",
  "gg",
  "qba",
  "qmp",
  "vqprd",
  "appellation",
  "controlee",
  "protegee",
  "d",
  "origine",
  "denominazione",
  "di",
  "origine_controllata",
  "controllata",
  "garantita",
  "e",
  "denominacion",
  "de",
  "origen",
  "calificada",
  "wine",
  "wines",
  "vin",
  "vino",
  "vinho",
  "wein",
  "region",
  "regional",
  "reserve",
  "reserva",
  "riserva",
  "superiore",
  "classico",
  "grand",
  "cru",
  "premier",
  "1er",
  "village",
  "villages",
  "cotes",
  "valley",
  "valle",
  "vallee",
  "vineyard",
  "vineyards",
  "estate",
  "single",
  "malt",
  "straight",
  "whisky",
  "whiskey",
]);

export function normalizeAppellationKey(raw: string): string {
  return raw
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[àáâä]/g, "a")
    .replace(/[èéêë]/g, "e")
    .replace(/[ìíîï]/g, "i")
    .replace(/[òóôö]/g, "o")
    .replace(/[ùúûü]/g, "u")
    .replace(/ç/g, "c")
    .replace(/ñ/g, "n")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function lookupJa(raw: string): string | null {
  const text = raw.normalize("NFKC").trim();
  if (!text) {
    return null;
  }
  const direct = VERIFIED_ORIGIN_BY_JA_APPELLATION[text];
  if (direct) {
    return direct;
  }
  const stripped = text.replace(/(都|道|府|県|産)$/u, "");
  return stripped !== text ? (VERIFIED_ORIGIN_BY_JA_APPELLATION[stripped] ?? null) : null;
}

/**
 * 産地表記から検証済みの生産国だけを返す。未知・曖昧（別の国に当たる語が混在）は null。
 * 完全一致 → 格付け語を除いた一致 → 連続する語の窓（長い順）で 1 か国に絞れるときだけ返す。
 */
export function countryFromVerifiedAppellation(raw: string): string | null {
  const ja = lookupJa(raw);
  if (ja) {
    return ja;
  }
  const key = normalizeAppellationKey(raw);
  if (!key) {
    return null;
  }
  const direct = VERIFIED_ORIGIN_BY_APPELLATION[key];
  if (direct) {
    return direct;
  }
  const tokens = key.split("_").filter((token) => token.length > 0);
  const meaningful = tokens.filter((token) => !QUALIFIER_TOKENS.has(token));
  const stripped = meaningful.join("_");
  if (stripped && stripped !== key && VERIFIED_ORIGIN_BY_APPELLATION[stripped]) {
    return VERIFIED_ORIGIN_BY_APPELLATION[stripped] ?? null;
  }
  const found = new Set<string>();
  for (let size = tokens.length; size >= 1; size -= 1) {
    for (let start = 0; start + size <= tokens.length; start += 1) {
      const phrase = tokens.slice(start, start + size).join("_");
      const country = VERIFIED_ORIGIN_BY_APPELLATION[phrase];
      if (country) {
        found.add(country);
      }
    }
    if (found.size > 0) {
      break;
    }
  }
  return found.size === 1 ? ([...found][0] ?? null) : null;
}
