export const BOTTLE_PHOTO_ACTION_LABELS = {
  frontHeading: "表面",
  backHeading: "裏ラベル",
  editPhoto: "写真を編集",
  editFrontPhoto: "表面の写真を編集",
  editBackPhoto: "裏ラベルの写真を編集",
  addBack: "＋ 裏ラベルを追加（任意）",
  addFrontPrompt: "ボトルの写真を追加",
  captureShort: "撮影",
  libraryShort: "ライブラリ",
  adjustCrop: "切り抜きを調整",
  recapture: "撮り直す",
  reselect: "写真を選び直す",
  deletePhoto: "写真を削除",
  captureBack: "裏ラベルを撮る",
  selectBack: "裏ラベルを選ぶ",
  addFrontCapture: "写真を撮る",
  addFrontLibrary: "写真を選ぶ",
  frontThumbAlt: "表面の写真",
  backThumbAlt: "裏ラベルの写真",
  frontProcessing: "表面を処理しています",
  backProcessing: "裏ラベルを処理しています",
  emptyPhoto: "写真なし",
  expandFront: "写真を拡大",
  expandBack: "裏ラベルの写真を拡大",
} as const;
